Repository Volue-Public/volue-insight-timeseries, pull requests merged in 2023-11, with the labels that each got.

#45 Update docs
  README.md
  docs/connect.rst
  docs/curves.rst
  docs/events.rst
  docs/examples.rst
  docs/install.rst
  docs/modules.rst
  docs/quickstart.rst
Labels: documentation

#44 :alien: Set dtype of empty series
  volue_insight_timeseries/util.py
Labels: feature

#46 docs: More renames for wapi
  docs/events.rst
  docs/quickstart.rst
  example/volue-insight-timeseries-notebook.ipynb
  examples/intraday_examples/absolute_intraday_price_forecast.py
  requirements.txt
  unittest/test_session.py
  volue_insight_timeseries/session.py
Labels: feature, dependencies
