Repository Volue-Public/volue-insight-timeseries, pull requests merged in 2023-12, with the labels that each got.

#49 Added lead time analysis example.
  examples/intraday_examples/lead_time_analysis.py
Labels: feature

#51 build: 2fa publish-pipeline
  .github/workflows/publish_package.yml
Labels: internal

#56 Correcting naming.
  examples/intraday_examples/lead_time_analysis.py
Labels: feature

#55 refactor: Moved mergerable
  .github/mergeable.yml
Labels: internal

#53 build: Update VERSION
  volue_insight_timeseries/VERSION
Labels: ignore-for-release
