Repository Volue-Public/volue-insight-timeseries, pull requests merged in 2024-05, with the labels that each got.

#84 fix(deps): Move dependencies used in examples to extras
  docs/examples.rst
  requirements.txt
Labels: dependencies

#81 fix(pandas): update frequencies for new pandas. Add warning
  .github/workflows/unittests.yml
  unittest/test_util.py
  volue_insight_timeseries/util.py
Labels: internal, feature

#89 build: Update VERSION
  volue_insight_timeseries/VERSION
Labels: ignore-for-release

#91 docs: update references to wapi
  docs/connect.rst
  docs/curves.rst
  docs/index.rst
  docs/modules.rst
  docs/quickstart.rst
  example/README.md
  examples/Instance_curve_examples/ins_latest_instance.py
  examples/Instance_curve_examples/ins_multiple_instances.py
  examples/Listening_for_changes/renewables_database.py
  examples/Tagged-Instance_curve_examples/tagins_latest_instance.py
  examples/Tagged-Instance_curve_examples/tagins_multiple_instances.py
  examples/Tagged-Instance_curve_examples/tagins_multiple_tags.py
  examples/Tagged-Instance_curve_examples/tagins_simple_read.py
  examples/Timeseries_curve_examples/ts_aggregation.py
  examples/Timeseries_curve_examples/ts_aggregation_timezone.py
  examples/general_examples/gen_aggregation_pandas.py
  examples/intraday_examples/absolute_intraday_price_forecast.py
  examples/intraday_examples/intraday_price_forecast.py
  examples/large_volume_examples/get_long_timeseries.py
Labels: documentation, feature

#93 build: Update VERSION
  volue_insight_timeseries/VERSION
Labels: ignore-for-release
